# Generated by Django 5.2.5 on 2026-02-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('period', models.CharField(help_text='e.g., 2023 - Present', max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Higher number comes first')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
