# Generated by Django 5.2.5 on 2026-02-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('period', models.CharField(help_text='e.g., 2016 – 2018', max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Higher number comes first')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
