# Generated by Django 5.2.5 on 2026-02-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField()),
                ('venue', models.CharField(help_text='e.g. NeurIPS 2023', max_length=100)),
                ('volume', models.CharField(blank=True, help_text='e.g. Volume XXIV', max_length=50, null=True)),
                ('authors', models.CharField(default='M. Aurelius, et al.', max_length=200)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
