# Generated by Django 5.2.5 on 2026-02-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilosophyTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='FontAwesome class, e.g., fa-compass', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='M. Aurelius', max_length=100)),
                ('hero_title', models.CharField(default='THE INTERSECTION OF WISDOM & CODE', max_length=200)),
                ('hero_tagline', models.TextField(default='Architecting the next generation of artificial intelligence with the precision of classical geometry.')),
                ('philosophy_intro', models.TextField(default='My approach to development is rooted in the belief that reason should be as ethical as it is efficient.')),
                ('email', models.EmailField(default='promitsrkr@gmail.com', max_length=254)),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/promitsarker')),
                ('github_url', models.URLField(default='https://github.com/PromitSarker')),
                ('resume_url', models.URLField(blank=True, help_text='Link to your PDF resume', null=True)),
            ],
        ),
    ]
