# Generated by Django 5.2.5 on 2026-02-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_philosophytrait_portfolioprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprofile',
            name='chronology_title',
            field=models.CharField(default='Chronology', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='contact_subtitle',
            field=models.TextField(default='"The Universe is change; our life is what our thoughts make it."'),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='contact_title',
            field=models.CharField(default='Initiate Dialogue', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='education_label',
            field=models.CharField(default='II. Formation (Education)', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='experience_label',
            field=models.CharField(default='I. Praxis (Experience)', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='hero_subtitle',
            field=models.CharField(default='Est. MMXXIV • Artificial Intelligence', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='philosophy_title',
            field=models.CharField(default='Ethics & Architecture', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='projects_title',
            field=models.CharField(default='Selected Works', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='publications_title',
            field=models.CharField(default='Publications', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioprofile',
            name='hero_title',
            field=models.CharField(default="THE INTERSECTION OF <br> <span class='italic text-gold'>WISDOM</span> & CODE", max_length=200),
        ),
    ]
