# Generated by Django 6.0.2 on 2026-02-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_portfolioprofile_chronology_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-order', '-date']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='The Algorithm', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='chronicles_subtitle',
            field=models.CharField(default='Scrolls', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='chronicles_title',
            field=models.CharField(default='The Chronicles', max_length=200),
        ),
    ]
