# Generated by Django 6.0.2 on 2026-02-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_skillcategory_portfolioprofile_armory_title_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. FOUNDATIONS', max_length=100)),
                ('subtitle', models.CharField(help_text='e.g. CORE ENGINEERING', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='armory_tagline',
            field=models.CharField(default='An architectural repository of technical proficiencies tailored for intelligent systems.', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolioprofile',
            name='name',
            field=models.CharField(default='Promit Sarker', max_length=100),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='pillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.skillpillar'),
        ),
    ]
