# Generated by Django 6.0.2 on 2026-02-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_skillpillar_portfolioprofile_armory_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imageUrl',
            field=models.URLField(blank=True, help_text='Fallback URL if no image is uploaded', null=True),
        ),
    ]
