# Generated by Django 6.0.2 on 2026-02-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_image_alter_project_imageurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_year', '-order']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_year', '-order']},
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(default=2000, help_text='Starting year for sorting'),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(default=2000, help_text='Starting year for sorting'),
        ),
    ]
